---
raspi:
  children:
    raspi-master:
      hosts:
        192.168.100.101:
          hostname: raspi01.home
    raspi-worker:
      hosts:
        192.168.100.102:
          hostname: raspi02.home
        192.168.100.103:
          hostname: raspi03.home
