---
raspi:
  children:
    raspi-master:
      hosts:
        192.168.10.115:
          hostname: raspi01.home
    raspi-worker:
      hosts:
        192.168.10.116:
          hostname: raspi02.home
        192.168.10.118:
          hostname: raspi03.home
