replicaCount: 1
image:
  repository: grafana/grafana
  tag: "10.2.0"
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 3000
adminUser: admin
adminSecret: grafana-admin-secret
prometheus:
  serviceName: prometheus-prometheus
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi
