replicaCount: 1

image:
  tag: "main"

service:
  type: ClusterIP

persistence:
  size: 20Gi

resources:
  requests:
    memory: "1Gi"
    cpu: "1000m"
  limits:
    memory: "2Gi"
    cpu: "2000m"

ollama:
  baseUrl: "http://ollama:11434"

env:
  - name: ENABLE_WEB_SEARCH
    value: "True"
  - name: WEB_SEARCH_ENGINE
    value: "searxng"
  - name: SEARXNG_QUERY_URL
    value: "http://searxng:8080/search?q=<query>&format=json"

ingress:
  enabled: true
  className: tailscale
  host: open-webui
  annotations:
    tailscale.com/proxy-group: ingress-proxies
    tailscale.com/hostname: open-webui
