replicaCount: 1

image:
  tag: "main"

service:
  type: ClusterIP

persistence:
  size: 20Gi

resources:
  requests:
    memory: "1Gi"
    cpu: "1000m"
  limits:
    memory: "2Gi"
    cpu: "2000m"

ollama:
  baseUrl: "http://ollama:11434"

ingress:
  enabled: true
  className: tailscale
  host: open-webui
  annotations:
    tailscale.com/proxy-group: ingress-proxies
