apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-grafana
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-grafana
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-grafana
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-grafana
    spec:
      containers:
        - name: grafana
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: GF_SECURITY_ADMIN_USER
              value: {{ .Values.adminUser | quote }}
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.adminSecret }}
                  key: admin-password
          ports:
            - containerPort: 3000
              name: http
          volumeMounts:
            - name: config
              mountPath: /etc/grafana/provisioning/datasources
            - name: dashboard-provisioning
              mountPath: /etc/grafana/provisioning/dashboards
            - name: dashboards
              mountPath: /etc/grafana/dashboards
            - name: data
              mountPath: /var/lib/grafana
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ .Release.Name }}-grafana-config
        - name: dashboard-provisioning
          configMap:
            name: {{ .Release.Name }}-grafana-dashboard-provisioning
        - name: dashboards
          configMap:
            name: {{ .Release.Name }}-grafana-dashboards
        - name: data
          emptyDir: {}
