apiVersion: v1
kind: Secret
metadata:
  name: steam-headless-secret
  labels:
    app: steam-headless
type: Opaque
stringData:
  NEKO_PASSWORD: {{ .Values.secret.nekoPassword | quote }}
  NEKO_PASSWORD_ADMIN: {{ .Values.secret.nekoPasswordAdmin | quote }}
