---
- name: Raspberry Pi 共通セットアップ
  hosts: raspi
  become: yes
  roles:
    - common

- name: k3s server セットアップ (master)
  hosts: raspi-master
  become: yes
  roles:
    - k3s

- name: k3s agent セットアップ (worker)
  hosts: raspi-worker
  become: yes
  roles:
    - k3s
