replicaCount: 1

image:
  tag: "latest"

service:
  type: ClusterIP

persistence:
  size: 50Gi

resources:
  requests:
    memory: "4Gi"
    cpu: "2000m"
    gpu: "1"
  limits:
    memory: "8Gi"
    cpu: "4000m"
    gpu: "1"

gpu:
  enabled: true

env:
  - name: OLLAMA_NUM_PARALLEL
    value: "1"
  - name: OLLAMA_MAX_LOADED_MODELS
    value: "1"

models:
  - gemma3:4b
  - qwen3.6:27b
  - gemma4:26b-a4b-it-q4_K_M

ingress:
  enabled: true
  className: tailscale
  annotations:
    tailscale.com/hostname: "ollama"
    tailscale.com/proxy-group: "ingress-proxies"
