replicaCount: 1

image:
  tag: "latest"

service:
  type: ClusterIP

persistence:
  size: 50Gi

resources:
  requests:
    memory: "4Gi"
    cpu: "2000m"
    gpu: "1"
  limits:
    memory: "8Gi"
    cpu: "4000m"
    gpu: "1"

gpu:
  enabled: true

models:
  - gemma3:4b
  - qwen3.6:27b
