# Pi-hole production environment values
image:
  repository: pihole/pihole
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

nodeSelector:
  node-role: worker

service:
  dns:
    type: LoadBalancer
    loadBalancerIP: 192.168.100.201
    port: 53
    nodePort: 30053
  web:
    type: ClusterIP
    port: 80
    nodePort: 30080

ingress:
  enabled: true
  className: tailscale
  host: pihole
  annotations:
    tailscale.com/proxy-group: ingress-proxies
    tailscale.com/hostname: pihole

persistence:
  enabled: true
  storageClass: "local-path"
  size: 5Gi

env:
  TZ: Asia/Tokyo
  WEBPASSWORD: "admin123"

adlists:
  - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
  - https://280blocker.net/files/280blocker_adblock_202602.txt
