apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ollama-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/obithree/obitwo_house_cluster.git
    targetRevision: main
    path: k8s/charts/llm/ollama
    helm:
      valueFiles:
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: llm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
