apiVersion: v1
kind: ConfigMap
metadata:
  name: searxng-config
  labels:
    app: searxng
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
data:
  settings.yml: |
    use_default_settings: true

    server:
      secret_key: {{ .Values.config.secretKey | quote }}
      {{- if .Values.config.baseUrl }}
      base_url: {{ .Values.config.baseUrl | quote }}
      {{- end }}
      limiter: false
      image_proxy: true

    ui:
      static_use_hash: true

    search:
      safe_search: 0
      autocomplete: ""
      default_lang: "ja-JP"
      formats:
        - html
        - json
