apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Release.Name }}-alloy
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-alloy
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-alloy
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-alloy
    spec:
      serviceAccountName: {{ .Release.Name }}-alloy
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      containers:
        - name: alloy
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - run
            - /etc/alloy/config.alloy
            - --server.http.listen-addr=0.0.0.0:12345
            - --storage.path=/tmp/alloy
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          ports:
            - containerPort: 12345
              name: http-metrics
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /etc/alloy
            - name: host-proc
              mountPath: /host/proc
              readOnly: true
            - name: host-sys
              mountPath: /host/sys
              readOnly: true
            - name: host-root
              mountPath: /host/root
              mountPropagation: HostToContainer
              readOnly: true
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ .Release.Name }}-alloy-config
        - name: host-proc
          hostPath:
            path: /proc
        - name: host-sys
          hostPath:
            path: /sys
        - name: host-root
          hostPath:
            path: /
