# ArgoCD default values

ingress:
  enabled: true
  className: nginx
  host: argocd.home.local
  port: 443

service:
  name: argocd-server
  port: 443

annotations:
  nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
