# ArgoCD default values

ingress:
  enabled: true
  className: nginx
  host: argocd.home.local
  port: 80

service:
  name: argocd-server
  port: 80

annotations:
  nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
