apiVersion: v2
name: longhorn
description: Longhorn distributed block storage for home cluster
type: application
version: 0.1.0

dependencies:
  - name: longhorn
    version: 1.7.2
    repository: https://charts.longhorn.io
