replicaCount: 1

image:
  repository: siutin/stable-diffusion-webui-docker
  tag: default-cuda-latest
  pullPolicy: IfNotPresent

resources:
  limits:
    nvidia.com/gpu: 1

env:
  - name: CLI_ARGS
    value: "--api --listen"
  - name: DOCKER_MODS
    value: "linuxserver/mods:stable-diffusion-webui-api"
