replicaCount: 1

image:
  repository: siutin/stable-diffusion-webui-docker
  tag: default-cpu-latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 7860

resources: {}
  # limits:
  #   nvidia.com/gpu: 1

persistence:
  enabled: true
  storageClass: "standard" # Assuming minikube or default storageclass
  size: 50Gi

env:
  - name: CLI_ARGS
    value: "--listen --api"
