---
- name: reboot
  reboot:
    reboot_timeout: 300

- name: update grub and reboot
  reboot:
    reboot_timeout: 300

- name: restart k3s-agent
  ansible.builtin.systemd:
    name: k3s-agent
    state: restarted
